"""Add ship_status to order

Revision ID: d7b319f7b487
Revises: d86b84a3cfe8
Create Date: 2026-01-14 14:04:19.402828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b319f7b487'
down_revision: Union[str, Sequence[str], None] = 'd86b84a3cfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ship_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'ship_status')
    # ### end Alembic commands ###
