"""Initial migration

Revision ID: d86b84a3cfe8
Revises: 
Create Date: 2025-12-30 10:57:13.304131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86b84a3cfe8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('cust_id', sa.Text(), nullable=True),
    sa.Column('cust_name', sa.Text(), nullable=True),
    sa.Column('ship_define_date', sa.Text(), nullable=False),
    sa.Column('ship_qty', sa.Text(), nullable=True),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('duties_type', sa.Text(), nullable=True),
    sa.Column('snapshot_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ship_define_date', 'item_id')
    )
    op.create_table('product',
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('search_name', sa.Text(), nullable=True),
    sa.Column('search_name2', sa.Text(), nullable=True),
    sa.Column('buyer_price', sa.Text(), nullable=True),
    sa.Column('del_flg', sa.Text(), nullable=True),
    sa.Column('create_dttm', sa.Text(), nullable=True),
    sa.Column('update_dttm', sa.Text(), nullable=True),
    sa.Column('item_rsv_col001', sa.Text(), nullable=True),
    sa.Column('item_rsv_col002', sa.Text(), nullable=True),
    sa.Column('item_rsv_col003', sa.Text(), nullable=True),
    sa.Column('item_rsv_col004', sa.Text(), nullable=True),
    sa.Column('item_rsv_col005', sa.Text(), nullable=True),
    sa.Column('item_rsv_col006', sa.Text(), nullable=True),
    sa.Column('item_rsv_col007', sa.Text(), nullable=True),
    sa.Column('item_rsv_col008', sa.Text(), nullable=True),
    sa.Column('item_rsv_col009', sa.Text(), nullable=True),
    sa.Column('item_rsv_col010', sa.Text(), nullable=True),
    sa.Column('snapshot_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('stock',
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('block_short_name', sa.Text(), nullable=True),
    sa.Column('loc', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('stock_qty', sa.Text(), nullable=True),
    sa.Column('assign_qty', sa.Text(), nullable=True),
    sa.Column('last_arv_date', sa.Text(), nullable=True),
    sa.Column('last_ship_date', sa.Text(), nullable=True),
    sa.Column('snapshot_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'loc', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
